import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, Clock3, LocateFixed, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { createQuickBookingPayload } from "@/lib/quickBooking";
import { trpc } from "@/lib/trpc";
import { useLocation } from "wouter";

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const delhiCentre = { latitude: 28.6139, longitude: 77.209 };

export default function QuickBook() {
  const [, navigate] = useLocation();
  const [area, setArea] = useState(""); const [day, setDay] = useState("Wednesday"); const [time, setTime] = useState("10:30"); const [selectedSlot, setSelectedSlot] = useState("Morning"); const [bookingCode, setBookingCode] = useState(""); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null);
  const currentLocation = location ?? delhiCentre; const previewInput = useMemo(() => ({ day, time, festival: false, latitude: currentLocation.latitude, longitude: currentLocation.longitude }), [currentLocation.latitude, currentLocation.longitude, day, time]);
  const preview = trpc.delivery.preview.useQuery(previewInput, { refetchInterval: 20_000 }); const slots = preview.data?.slots ?? []; const best = slots.length ? [...slots].sort((a, b) => b.score - a.score)[0] : undefined; const chosen = slots.find(slot => slot.label === selectedSlot) ?? best;
  const utils = trpc.useUtils(); const book = trpc.delivery.book.useMutation({ onSuccess: result => { setBookingCode(result.delivery.trackingCode); toast.success("Your delivery time is booked"); utils.delivery.preview.invalidate(); utils.delivery.route.invalidate(); } });
  const useMyLocation = () => { if (!navigator.geolocation) { toast.error("Location is unavailable in this browser"); return; } navigator.geolocation.getCurrentPosition(position => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); toast.success("Your location is now being used"); }, () => toast.error("Location permission was not granted"), { enableHighAccuracy: true, timeout: 10_000 }); };
  const bookSlot = () => { if (area.trim().length < 3) { toast.error("Please enter your area or landmark"); return; } if (!chosen) return; book.mutate(createQuickBookingPayload({ area, day, time, selectedSlot: chosen.label, ...currentLocation })); };
  useEffect(() => { if (localStorage.getItem("samaysetu-customer-demo") !== "open") navigate("/"); }, [navigate]);
  return <main className="quick-book-page"><section className="quick-book-intro"><p className="eyebrow">SIMPLE BOOKING</p><h1>Book your delivery<br /><em>in three easy steps.</em></h1><p>Tell us your area and preferred time. We will show the delivery time that is easiest to keep.</p></section><section className="quick-book-card"><div className="quick-form"><div className="quick-step"><span>1</span><div><label htmlFor="quick-area">Where should we deliver?</label><small>Area or nearby landmark</small></div></div><div className="quick-input"><MapPin size={20} /><input id="quick-area" value={area} onChange={event => setArea(event.target.value)} placeholder="Example: Laxmi Nagar, East Delhi" /></div><button className="quick-location-button" onClick={useMyLocation}><LocateFixed size={16} /> {location ? "Your location is being used" : "Use my current location"}</button><small className="quick-estimate-note">{location ? "Your own location is included in the time check." : "Showing a Delhi estimate until you share your location."}</small><div className="quick-step"><span>2</span><div><label>When do you prefer?</label><small>Choose a day and time</small></div></div><div className="quick-two-fields"><div className="quick-input"><CalendarDays size={19} /><select value={day} onChange={event => setDay(event.target.value)}>{weekdays.map(item => <option key={item}>{item}</option>)}</select></div><div className="quick-input"><Clock3 size={19} /><input type="time" value={time} onChange={event => setTime(event.target.value)} /></div></div></div><aside className="quick-prediction"><div className="quick-step"><span>3</span><div><label>Choose your delivery time</label><small>We check road traffic, weather and the delivery route for you.</small></div></div>{preview.isLoading ? <div className="quick-loading">Finding the best delivery time…</div> : <><div className="quick-best"><p>BEST TIME FOR YOU</p><strong>{best?.range ?? "Checking…"}</strong><span>{best?.score ?? 0}% chance of arriving on time</span></div><div className="quick-slot-list">{slots.map(slot => <button key={slot.label} onClick={() => setSelectedSlot(slot.label)} className={chosen?.label === slot.label ? "selected" : ""}><span><b>{slot.label}</b><small>{slot.range}</small></span><strong>{slot.score}%</strong></button>)}</div><button className="quick-book-action" disabled={book.isPending || !chosen} onClick={bookSlot}><span>{book.isPending ? "Booking your time…" : "Book this slot"}<small>{chosen ? `${chosen.label} · ${chosen.range}` : "Choose a time first"}</small></span><ArrowRight size={22} /></button></>}<div className="quick-promise"><ShieldCheck size={18} /><span><b>Only suitable times are shown.</b><small>We do not show a time if the postman route is too busy.</small></span></div>{bookingCode && <div className="quick-success"><Sparkles size={17} /><span><b>Booking confirmed</b><small>Keep this number: {bookingCode}</small></span></div>}</aside></section></main>;
}
