import { and, desc, eq, gte, inArray, ne, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { deliveries, deliveryEvents, deliveryFiles, deliveryNotificationOutbox, type InsertUser, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let database: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!database && process.env.DATABASE_URL) database = drizzle(process.env.DATABASE_URL); return database; }
export async function upsertUser(user: InsertUser) { const db = await getDb(); if (!db) return; await db.insert(users).values({ ...user, role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user"), lastSignedIn: user.lastSignedIn ?? new Date() }).onDuplicateKeyUpdate({ set: { name: user.name, email: user.email, loginMethod: user.loginMethod, lastSignedIn: new Date() } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0]; }
export async function saveDeliveryProof(input: { userId: number; deliveryId: string; fileName: string; fileKey: string; fileUrl: string; mimeType: string; sizeBytes: number }) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); await db.insert(deliveryFiles).values(input); return input; }
export async function listDeliveryProofs(userId: number, deliveryId: string) { const db = await getDb(); if (!db) return []; return db.select().from(deliveryFiles).where(and(eq(deliveryFiles.userId, userId), eq(deliveryFiles.deliveryId, deliveryId))).orderBy(desc(deliveryFiles.createdAt)); }
export async function getLiveSignals() { const db = await getDb(); if (!db) return { activeCount: 0, completed24h: 0, rescheduled24h: 0 }; const since = new Date(Date.now() - 86_400_000); const active = await db.select({ count: sql<number>`count(*)` }).from(deliveries).where(inArray(deliveries.status, ["booked", "assigned", "out_for_delivery"])); const recent = await db.select({ eventType: deliveryEvents.eventType }).from(deliveryEvents).where(gte(deliveryEvents.createdAt, since)); return { activeCount: Number(active[0]?.count ?? 0), completed24h: recent.filter(event => event.eventType === "delivered").length, rescheduled24h: recent.filter(event => event.eventType === "rescheduled").length }; }
export async function createDelivery(input: { trackingCode: string; area: string; latitude: string; longitude: string; requestedDay: string; preferredTime: string; selectedSlot: string; predictedScore: number }) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); const result = await db.insert(deliveries).values(input); const id = Number(result[0].insertId); await db.insert(deliveryEvents).values({ deliveryId: id, eventType: "booked", note: `Delivery request created for ${input.selectedSlot}.` }); return { id, ...input, status: "booked" as const, createdAt: new Date() }; }
export async function queueDeliveryNotification(input: { deliveryId: number; trackingCode: string; eventType: string; channels: string; providerState: "provider_required" | "queued" }) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); await db.insert(deliveryNotificationOutbox).values(input); return input; }
export async function getDeliveryByCode(trackingCode: string) { const db = await getDb(); if (!db) return undefined; const delivery = (await db.select().from(deliveries).where(eq(deliveries.trackingCode, trackingCode)).limit(1))[0]; if (!delivery) return undefined; const events = await db.select().from(deliveryEvents).where(eq(deliveryEvents.deliveryId, delivery.id)).orderBy(desc(deliveryEvents.createdAt)); return { delivery, events }; }
export async function listRouteDeliveries() { const db = await getDb(); if (!db) return []; return db.select().from(deliveries).where(ne(deliveries.status, "delivered")).orderBy(desc(deliveries.createdAt)).limit(12); }
export async function updateDeliveryStatus(id: number, status: "assigned" | "out_for_delivery" | "delivered" | "rescheduled", note: string) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); await db.update(deliveries).set({ status }).where(eq(deliveries.id, id)); await db.insert(deliveryEvents).values({ deliveryId: id, eventType: status, note }); return getDeliveryById(id); }
export async function recordPostmanNearby(id: number) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); await db.insert(deliveryEvents).values({ deliveryId: id, eventType: "postman_nearby", note: "Your delivery person is close. Please be ready to receive your article." }); return getDeliveryById(id); }
export async function getDeliveryById(id: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(deliveries).where(eq(deliveries.id, id)).limit(1))[0]; }
