export type DeliverySignal = { activeCount: number; completed24h: number; rescheduled24h: number };
export type OperationalSignal = { weather: { scoreImpact: number; label: string }; traffic: { scoreImpact: number; label: string } };
export type SlotScore = { label: string; range: string; score: number; reasons: string[] };

const windows = [{ label: "Morning", range: "09:00 — 11:00", hour: 10, base: 82 }, { label: "Midday", range: "11:00 — 13:00", hour: 12, base: 78 }, { label: "Afternoon", range: "13:00 — 15:00", hour: 14, base: 73 }, { label: "Late day", range: "15:00 — 17:00", hour: 16, base: 68 }, { label: "Evening", range: "17:00 — 19:00", hour: 18, base: 60 }];

export function scoreDeliverySlots(input: { day: string; time: string; festival: boolean; signals: DeliverySignal; operational?: OperationalSignal }): SlotScore[] {
  const [hours, minutes] = input.time.split(":").map(Number); const wanted = hours + minutes / 60; const weekend = ["Saturday", "Sunday"].includes(input.day); const workloadPenalty = Math.min(16, input.signals.activeCount * 2); const recoveryLift = Math.min(5, Math.floor(input.signals.completed24h / 2)); const reschedulePenalty = Math.min(8, input.signals.rescheduled24h * 2); const weatherPenalty = input.operational?.weather.scoreImpact ?? 0; const trafficPenalty = input.operational?.traffic.scoreImpact ?? 0;
  return windows.map(window => { const timeFit = Math.round(Math.max(-12, 14 - Math.abs(wanted - window.hour) * 2.5)); const slotLoad = window.label === "Evening" ? -5 : window.label === "Morning" ? 3 : 0; const weekendAdjustment = weekend && window.label !== "Evening" ? 2 : 0; const holidayAdjustment = input.festival ? (window.label === "Morning" ? -7 : -4) : 0; const score = Math.max(35, Math.min(98, window.base + timeFit + slotLoad + weekendAdjustment + holidayAdjustment - workloadPenalty + recoveryLift - reschedulePenalty - weatherPenalty - trafficPenalty)); const reasons = [`Requested time contributes ${timeFit >= 0 ? "+" : ""}${timeFit} points.`, input.signals.activeCount ? `${input.signals.activeCount} active deliveries contribute -${workloadPenalty} workload points.` : "No active delivery workload is currently recorded.", input.operational ? `${input.operational.weather.label} contributes -${weatherPenalty} weather points and ${input.operational.traffic.label.toLowerCase()} contributes -${trafficPenalty} traffic points.` : "Operational weather and traffic signals are not yet available.", input.signals.completed24h ? `${input.signals.completed24h} delivery completion${input.signals.completed24h === 1 ? "" : "s"} in the last 24 hours contributes +${recoveryLift} service-capacity points.` : "No last-24-hour completions have been recorded yet.", input.festival ? `Festival setting contributes ${holidayAdjustment} demand points.` : "No festival demand adjustment was applied."]; return { label: window.label, range: window.range, score, reasons }; });
}
