/// <reference types="@types/google.maps" />
import { useCallback, useEffect, useMemo, useState } from "react";
import { Layers3, MapPin, Navigation } from "lucide-react";
import { MapView } from "@/components/Map";
import { buildShortestRoute, spreadOverlappingDots } from "@/lib/shortestRoute";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export type LiveRouteStop = { id: string; label: string; lat: number; lng: number; status?: "hub" | "delivered" | "next" | "pending" | "customer"; x: number; y: number; };
const DelhiLabels = [{ name: "Rohini", x: 20, y: 17 }, { name: "North Delhi", x: 48, y: 18 }, { name: "Shahdara", x: 81, y: 34 }, { name: "Dwarka", x: 18, y: 73 }, { name: "Central Delhi", x: 47, y: 48 }, { name: "Mayur Vihar", x: 76, y: 58 }, { name: "Saket", x: 49, y: 81 }];

function NearbyUpdateButton({ deliveryId }: { deliveryId?: string }) { const utils = trpc.useUtils(); const [queued, setQueued] = useState(false); useEffect(() => setQueued(false), [deliveryId]); const nearby = trpc.delivery.demoMarkNearby.useMutation({ onSuccess: () => { setQueued(true); utils.delivery.route.invalidate(); toast.success("Recipient update queued", { description: "SMS or WhatsApp will send once a provider is connected." }); } }); if (!deliveryId || deliveryId === "hub" || Number.isNaN(Number(deliveryId))) return null; return <button className="nearby-map-action" disabled={nearby.isPending || queued} onClick={() => nearby.mutate({ id: Number(deliveryId) })}>{nearby.isPending ? "Sending update…" : queued ? "Recipient update queued" : "Postman is close"}<small>{queued ? "SMS / WhatsApp sends when connected" : "Tell customer to be ready"}</small></button>; }
function DelhiOperationsFallback({ stops, selectedId, onSelect, estimatedKm, postmanMode }: { stops: LiveRouteStop[]; selectedId?: string; onSelect?: (id: string) => void; estimatedKm: number; postmanMode: boolean }) {
  const active = stops.find(stop => stop.id === selectedId) ?? stops[stops.length - 1] ?? stops[0]; const routePoints = stops.filter(stop => stop.status === "hub" || stop.id === selectedId).map(stop => `${stop.x},${stop.y}`).join(" ");
  return <section className="delhi-map-panel" aria-label="Selected delivery route map"><div className="delhi-map-toolbar"><span><Layers3 size={14} /> Selected delivery route</span><span className="map-live"><i /> Route checked</span><span><MapPin size={14} /> {active?.label ?? "Choose a delivery"}</span></div><div className="delhi-map-surface"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Selected delivery route across Delhi"><path className="delhi-water" d="M82 -5 C76 12 84 25 80 39 S77 65 88 104" /><path className="delhi-boundary" d="M9 32 C18 12 41 4 59 10 S91 25 92 49 S80 82 56 91 S20 86 8 62 S1 44 9 32" /><path className="delhi-highway h1" d="M-4 69 C16 63 29 51 43 49 S70 47 104 32" /><path className="delhi-highway h2" d="M26 -3 C28 19 37 28 49 43 S63 75 73 103" /><path className="delhi-highway h3" d="M-4 27 C17 32 28 36 43 34 S74 17 104 16" /><path className="delhi-road r1" d="M7 84 C21 71 24 55 39 61 S61 80 90 70" /><path className="delhi-road r2" d="M9 8 C18 22 29 21 39 30 S58 45 74 45 S89 51 102 59" /><path className="delhi-road r3" d="M14 48 C31 43 36 33 50 37 S74 69 95 86" /><path className="delhi-road r4" d="M58 5 C54 21 63 29 59 42 S45 72 40 98" /><polyline className="delhi-route-halo" points={routePoints} /><polyline className="delhi-route" points={routePoints} /></svg>{DelhiLabels.map(label => <span className="delhi-district" key={label.name} style={{ left: `${label.x}%`, top: `${label.y}%` }}>{label.name}</span>)}{stops.map((stop, index) => <button key={stop.id} className={`delhi-stop ${stop.status ?? "pending"} ${active?.id === stop.id ? "selected" : ""}`} style={{ left: `${stop.x}%`, top: `${stop.y}%` }} onClick={() => onSelect?.(stop.id)} aria-label={`Choose ${stop.label}`}><span>{stop.status === "hub" ? "D" : index}</span><b>{stop.label}</b></button>)}<div className="delhi-map-controls"><button aria-label="Route overview"><Navigation size={15} /></button><button aria-label="Delhi coverage">DEL</button></div>{postmanMode && <NearbyUpdateButton deliveryId={selectedId} />}</div><div className="delhi-map-footer"><span><i className="hub-dot" /> Start point</span><span><i className="active-dot" /> Selected booking</span><span><i className="route-dot" /> Direct route preview</span><b>About {estimatedKm} km · Tap any dot</b></div></section>;
}

export function LiveRouteMap({ stops, selectedId, routeOriginId, onSelect, className }: { stops: LiveRouteStop[]; selectedId?: string; routeOriginId?: string; onSelect?: (id: string) => void; className?: string }) {
  const center = useMemo(() => ({ lat: 28.6139, lng: 77.2090 }), []); const visibleStops = useMemo(() => spreadOverlappingDots(stops), [stops]); const plan = useMemo(() => buildShortestRoute(visibleStops, selectedId, routeOriginId), [routeOriginId, selectedId, visibleStops]); const routeStops = plan.orderedStops;
  const drawRoute = useCallback((map: google.maps.Map) => { const path = routeStops.map(stop => ({ lat: stop.lat, lng: stop.lng })); const bounds = new google.maps.LatLngBounds(); new google.maps.TrafficLayer().setMap(map); const destination = path[path.length - 1]; if (path.length > 1 && destination) { const directions = new google.maps.DirectionsService(); const renderer = new google.maps.DirectionsRenderer({ map, suppressMarkers: true, preserveViewport: true, polylineOptions: { strokeColor: "#C9252D", strokeOpacity: .9, strokeWeight: 6 } }); directions.route({ origin: path[0], destination, waypoints: routeStops.slice(1, -1).map(stop => ({ location: { lat: stop.lat, lng: stop.lng }, stopover: true })), travelMode: google.maps.TravelMode.DRIVING, drivingOptions: { departureTime: new Date(), trafficModel: google.maps.TrafficModel.BEST_GUESS } }, (result, status) => { if (status === google.maps.DirectionsStatus.OK && result) renderer.setDirections(result); else new google.maps.Polyline({ map, path, strokeColor: "#C9252D", strokeOpacity: .9, strokeWeight: 4, geodesic: true }); }); } visibleStops.forEach((stop, index) => { const selected = stop.id === selectedId; const color = selected ? "#C9252D" : stop.status === "hub" ? "#CA2830" : "#E0A41A"; const marker = new google.maps.Marker({ map, position: { lat: stop.lat, lng: stop.lng }, title: stop.label, label: { text: stop.status === "hub" ? "D" : `${index}`, color: "#FFFFFF", fontWeight: "700", fontSize: "11px" }, icon: { path: google.maps.SymbolPath.CIRCLE, fillColor: color, fillOpacity: 1, strokeColor: "#FFFDF8", strokeWeight: selected ? 5 : 3, scale: selected ? 11 : 9 }, zIndex: selected ? 10 : undefined }); marker.addListener("click", () => onSelect?.(stop.id)); bounds.extend(marker.getPosition()!); }); if (visibleStops.length > 1) map.fitBounds(bounds, 58); else map.setCenter(center); }, [center, onSelect, routeStops, selectedId, visibleStops]);
  const postmanMode = Boolean(className?.includes("field-map")); return <div className="live-route-shell"><MapView className={`delhi-live-map ${className ?? ""}`} initialCenter={center} initialZoom={11} onMapReady={drawRoute} fallback={<DelhiOperationsFallback stops={visibleStops} selectedId={selectedId} onSelect={onSelect} estimatedKm={plan.estimatedKm} postmanMode={false} />} />{postmanMode && <NearbyUpdateButton deliveryId={selectedId} />}</div>;
}
